import { Metadata } from "next";

export const metadata: Metadata = {
  title: "PRINCING",
  description: "Generated by create PRINCING",
};
const PricingPage = () => {
  return (
    <div>Princing Page</div>
  )
}

export default PricingPage