import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "ABOUT",
  description: "Generated by create ABOUT",
};





const AboutPage = () => {
  return (
    <div className="text-7xl">
      <Link href="/contact" className="text-3xl text-blue-500">
        Go to Contact Page
      </Link>
      </div>
  )
}

export default AboutPage