import { Metadata } from "next";

export const metadata: Metadata = {
  title: "CONTACT",
  description: "Generated by create CONTACT",
};
const ContactPage = () => {
  return (
    <div>Contact Page</div>
  )
}

export default ContactPage